### ISSUE TITLE
无法检测到lsp框架

### ISSUE THREAD

**Issue by mhunice** [eswd04/freeform_update#7]
如图 已经在lsp管理器中启用模块，但应用内无法检测到。设备：OnePlus 8 系统：nameless rom，Android 13
![Screenshot_20230821-203355_Pixel 启动器](https://github.com/eswd04/freeform_update/assets/63174737/4780bd69-b132-4800-9e73-0300d062a973)

**Comment by eswd04** [comment]
请确认勾选后已重启了系统。若依旧显示未激活，请提供一下有效的日志，如lsposed日志等。

**Comment by mhunice** [comment]
您好 请问如何获取单个模块的日志

**Comment by mhunice** [comment]
> 请确认勾选后已重启了系统。若依旧显示未激活，请提供一下有效的日志，如lsposed日志等。
请问如何获取单个模块的日志

**Comment by PKQandBaaad** [comment]
我也遇到了相同的问题，以下是我的lsp部分日志

[ 2024-07-12T18:08:50.938    10252:  5467:  5467 E/LSPosed-Bridge  ] RUnWbRulRTLzeZfbaGsSOl.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.demo.myfreeform.recode.BaseViewModel
	at RUnWbRulRTLzeZfbaGsSOl.XposedHelpers.findClass(Unknown Source:12)
	at RUnWbRulRTLzeZfbaGsSOl.XposedHelpers.findAndHookMethod(SourceFile:6)
	at com.demo.myfreeform.hook.HookSelf.handleLoadPackage(:2)
	at RUnWbRulRTLzeZfbaGsSOl.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at RUnWbRulRTLzeZfbaGsSOl.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at RUnWbRulRTLzeZfbaGsSOl.callbacks.XCallback.callAll(Unknown Source:26)
	at h0.a(Unknown Source:320)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:253)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1130)
	at android.app.LoadedApk.getResources(LoadedApk.java:1378)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3336)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3327)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7277)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8592)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.ClassNotFoundException: com.demo.myfreeform.recode.BaseViewModel
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:607)
	at q.a(Unknown Source:16)
	at RUnWbRulRTLzeZfbaGsSOl.XposedHelpers.findClass(Unknown Source:4)
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.demo.myfreeform.recode.BaseViewModel
	... 27 more
